### ISSUE TITLE
Unable to find a type adapter for java.sql.Timestamp

### ISSUE THREAD

**Issue by abhsrivastava** [gzoller/ScalaJack#138]
I have written this code in my project

```
   def unmarshall[T](json: String)(implicit m: Manifest[T]): T = {
      implicit val formats = Serialization.formats(NoTypeHints)
      val sj = ScalaJack()
         .withAdapters(JodaDateTimeAdapter, SqlDateTimeAdapter)
      val result = sj.read[T](json)
      result
   }
object JodaDateTimeAdapter extends BasicTypeAdapter [DateTime] {
   override def read(reader: Reader): DateTime = {
      reader.peek match {
         case TokenType.String =>
            val raw = reader.readString()
            Try {
               new DateTime(raw.toLong)
            }.recover{
               case nfe : NumberFormatException => DateTime.parse(raw, ISODateTimeFormat.dateTimeParser())
            }.get
         case TokenType.Null =>
            reader.readNull()
      }
   }

   override def write(value: DateTime, writer: Writer): Unit =
      if (value == null) {
         writer.writeNull()
      } else {
         writer.writeString(value.getMillis.toString)
      }
}

object SqlDateTimeAdapter extends BasicTypeAdapter [Timestamp] {
   override def read(reader: Reader): Timestamp = {
      reader.peek match {
         case TokenType.String =>
            val raw = reader.readString()
            Try {
               val jodaTime = new DateTime(raw.toLong)
               new Timestamp(jodaTime.getMillis)
            }.recover{
               case nfe : NumberFormatException =>
                  val jodaTime = DateTime.parse(raw, ISODateTimeFormat.dateTimeParser())
                  new Timestamp(jodaTime.getMillis)
            }.get
         case TokenType.Null =>
            reader.readNull()
      }
   }

   override def write(value: Timestamp, writer: Writer): Unit =
      if (value == null) {
         writer.writeNull()
      } else {
         writer.writeString(value.getTime.toString)
      }
}
```
But still when I run my code and I try to parse some Json. I get errors

java.lang.IllegalArgumentException: Unable to find a type adapter for java.sql.Timestamp
	at co.blocke.scalajack.DefaultTypeAdapterFactory$.typeAdapterOf(DefaultTypeAdapterFactory.scala:8)
	at co.blocke.scalajack.TypeAdapterFactory$class.typeAdapterOf(TypeAdapterFactory.scala:55)
	at co.blocke.scalajack.DefaultTypeAdapterFactory$.typeAdapterOf(DefaultTypeAdapterFactory.scala:5)
	at co.blocke.scalajack.TypeAdapterFactory$$anon$1.typeAdapterOf(TypeAdapterFactory.scala:12)
	at co.blocke.scalajack.TypeAdapterFactory$class.typeAdapterOf(TypeAdapterFactory.scala:55)
	at co.blocke.scalajack.TypeAdapterFactory$$anon$1.typeAdapterOf(TypeAdapterFactory.scala:10)
	at co.blocke.scalajack.typeadapter.PlainClassTypeAdapter$.typeAdapterOf(PlainClassTypeAdapter.scala:244)
	at co.blocke.scalajack.TypeAdapterFactory$FromClassSymbol$class.typeAdapterOf(TypeAdapterFactory.scala:40)
	at co.blocke.scalajack.typeadapter.PlainClassTypeAdapter$.typeAdapterOf(PlainClassTypeAdapter.scala:22)
	at co.blocke.scalajack.TypeAdapterFactory$$anon$2.typeAdapterOf(TypeAdapterFactory.scala:18)
	at co.blocke.scalajack.TypeAdapterFactory$class.typeAdapterOf(TypeAdapterFactory.scala:55)

**Comment by gzoller** [comment]
Confirm issue -- able to duplicate reported result.  Investigating.

**Comment by gzoller** [comment]
I think I've found it.  For your two custom type adapters, extend SimpleTypeAdapter rather than BasicTypeAdapater.  SimpleTypeAdapter is almost always the right choice for base adapter, except for a primitive.  Simple uses =:= to test for type equality (while finding the right TypeAdapter) while Basic uses ==, which is so strict it can be fooled into returning a false negative (non-match), which is what I think happened here.  

Using your code above, switching to extending SimpleTypeAdapter worked for me, so I'm closing the issue.  If switching to SimpleTypeAdapter doesn't work for you, please re-open the issue.

One minor add--since you're rendering your timestamps as Strings, I recommend adding the mixin "with StringKind" to your TypeAdapter objects.  It's a marker trait that's used for Map keys, i.e. Map[TimeStamp, ...].   StringKind let's ScalaJack know it doesn't have to wrap the key value in quotes because that field is already rendering as a quoted String.

```
Output without StringKind mixin: 
{"\"1480915347869\"":"Fred"}

Output with StringKind mixin:
{"1480915347869":"Fred"}
```

Not sure if you're new to ScalaJack, but I hope you enjoy version 5!  Entirely new engine from series 4.  Feedback welcome.  Good luck!
