### ISSUE TITLE
AnyType interprets string as a number

### ISSUE THREAD

**Issue by Philippus** [gzoller/ScalaJack#170]
In version 6.0.0 the AnyTypeAdapter interpets string values like "5" as a BigInt.
Previously this was a string. I think it's common that string values sometimes by coincidence will contain an integer, but not always. In my case the "sub" claim in a JSON Web token.
I'd expect a string to remain a string and not change types based on its contents.

**Comment by gzoller** [comment]
I’ll take a look, but Any is a sadly messy affair on a good day.  Non-string Map keys are encoded as strings and decoded best-effort to their “native” types.  That’s an imperfect accommodation for json only supporting string-typed keys.  For non-map keys I’ll see what Any is doing.

**Comment by gzoller** [comment]
Done initial investigation.  Map keys aren't the issue.  It's treating "regular" Any like it does map keys.  Working to differentiate the two.  I may wire in the allowPermissivePrimitives flag (default set to false), so that if it is set to true you get the behavior you see now, giving the user a choice how Any string values are interpreted.

**Comment by gzoller** [comment]
Closing.  6.0.1 will fix this--release imminent.  Default setting (for non-map-keys) will leave strings as strings.  If you *do* want the "smart" interpretation you can set ScalaJack().allowPermissivePrimitives() and you'll see the behavior you saw here, so now you're in control.

**Comment by Philippus** [comment]
Thanks for the quick fix!
